SELECT
 YEAR(o.SALES_DATE) YEAR,
 MONTH(o.SALES_DATE) MONTH,
 u.GENDER,
 COUNT(DISTINCT u.USER_ID) USERS
FROM USER_INFO u
JOIN ONLINE_SALE o ON u.USER_ID = o.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER