SELECT
 a.PRODUCT_ID,
 a.PRODUCT_NAME,
 SUM(PRICE * AMOUNT) TOTAL_SALES
FROM FOOD_PRODUCT a
INNER JOIN FOOD_ORDER b 
ON a.PRODUCT_ID = b.PRODUCT_ID
WHERE PRODUCE_DATE BETWEEN '2022-05-01 00:00:00' AND '2022-05-31 00:00:00'
GROUP BY a.PRODUCT_ID, a.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, a.PRODUCT_ID